language: scala

scala:
  - 2.10.2

# only trigger builds on master
branches:
  only:
    - master

script:
  - "sbt \"project blue-test\" scenario:test"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq jsvc

